blog/article/urls.py
from django.conf.urls import url
from article import views


urlpatterns = [
    url(r'^$', views.article, name='article'),
    url(r'^articleCreate/$', views.articleCreate, name='articleCreate'),
    url(r'^articleRead/(?P<articleId>[0-9]+)/$', views.articleRead, name='articleRead'),
    url(r'^articleUpdate/(?P<articleId>[0-9]+)/$', views.articleUpdate, name='articleUpdate'),
    url(r'^articleDelete/(?P<articleId>[0-9]+)/$', views.articleDelete, name='articleDelete'),
    url(r'^articleSearch/$', views.articleSearch, name='articleSearch'),
]

blog/blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^main/', include('main.urls', namespace='main')),
    url(r'^article/', include('article.urls', namespace='article')),
    url(r'^book/', include('book.urls', namespace='book')),
    url(r'^.*', include('main.urls')),
    
]

blog/article/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=128, unique=True)
    content = models.TextField()
    pubDateTime = models.DateTimeField(auto_now_add=True)
    likes = models.IntegerField(default=0)
    
    
    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ('-pubDateTime', )
    

    
    
class Comment(models.Model):
    article = models.ForeignKey(Article)
    content = models.CharField(max_length=128)
    pubDateTime = models.DateTimeField(auto_now_add=True)
    
    
    def __str__(self):
        return self.article.title + '-' + str(self.id)
    

    
    

blog/article/forms.py
from django import forms
from article.models import Article


class ArticleForm(forms.ModelForm):
    title = forms.CharField(label='標題', max_length=128)
    content = forms.CharField(label='內容', widget=forms.Textarea)
    
    class Meta:
        model = Article
        fields = ['title', 'content']

blog/article/views.py
from django.contrib import messages
from django.db.models.query_utils import Q
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

from article.forms import ArticleForm
from article.models import Article, Comment
from main.views import admin_required


def article(request):
    '''
    Render the article page
    '''
    articles = Article.objects.all()
    
    itemArray = []
    for article in articles:
        items = [article]
        items.extend(list(Comment.objects.filter(article=article)))
        itemArray.append(items)
    context = {'itemArray':itemArray}
    return render(request, 'article/article.html', context)

@login_required
def articleCreate(request):
    template = 'article/articleCreateUpdate.html'
    if request.method == 'GET':
        return render(request, template, {'articleForm':ArticleForm()})
    # POST
    articleForm = ArticleForm(request.POST)
    if not articleForm.is_valid():
        return render(request, template, {'articleForm':articleForm})
    articleForm.save()
    messages.success(request, '文章已新增')
    return redirect('article:article')


def articleRead(request, articleId):
    '''
    Read an article
        1. Get the "article" instance; redirect to the 404 page if not found
        2. Render the articleRead template with article instance and its
        associated comments
    '''
    articleToRead = get_object_or_404(Article, id=articleId)
    context = {
        'article': articleToRead,
        'comments': Comment.objects.filter(article=articleToRead)
    }
    return render(request, 'article/articleRead.html', context)

@admin_required
def articleUpdate(request, articleId):
    '''
    Update the article instance:
        1. Get the article to update; redirect to 404 if not found
        2. Render a bound form if the method is GET
        3. If the form is valid, save it to the model, otherwise render a
        bound form with error messages
    '''
    articleToUpdate = get_object_or_404(Article, id=articleId)
    template = 'article/articleCreateUpdate.html'
    if request.method == 'GET':
        articleForm = ArticleForm(instance=articleToUpdate)
        return render(request, template, {'articleForm':articleForm, 'article':articleToUpdate})
    # POST
    articleForm = ArticleForm(request.POST, instance=articleToUpdate)
    if not articleForm.is_valid():
        return render(request, template, {'articleForm':articleForm, 'article':articleToUpdate})
    articleForm.save()
    messages.success(request, '文章已修改')
    return redirect('article:articleRead', articleId=articleId)

@admin_required
def articleDelete(request, articleId):
    '''
    Delete the article instance:
        1. Render the article page if the method is GET
        2. Get the article to delete; redirect to 404 if not found
    '''
    if request.method == 'GET':
        return article(request)
    # POST
    articleToDelete = get_object_or_404(Article, id=articleId)
    articleToDelete.delete()
    messages.success(request, '文章已刪除')
    return redirect('article:article')
    
    
def articleSearch(request):
    '''
    Search for articles:
        1. Get the "searchTerm" from the HTML page
        2. Use "searchTerm" for filtering
    '''
    searchTerm = request.GET.get('searchTerm')
    articles = Article.objects.filter(Q(title__icontains=searchTerm) |
                                      Q(content__icontains=searchTerm))
    context = {'articles':articles, 'searchTerm':searchTerm}
    return render(request, 'article/articleSearch.html', context)
    
    
    
    
    
    
    
    

blog/article/templates/article/article.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% block css %}
<link rel="stylesheet" href="{% static 'article/css/article.css' %}">
{% endblock %}
{% block heading %}歡迎蒞臨{% endblock %}
{% block content %}
{% include 'article/searchForm.html' %}
<br>
{% if user.is_superuser %}
  <p class="inlineBlock"><a class="btn" href="{% url 'article:articleCreate' %}">新增文章</a>
{% endif %}
<br><br><hr>
{% for items in itemArray %}
  {% for item in items %}
    {% if forloop.first %}
      <h3 class="inlineBlock"><a href="{% url 'article:articleRead' item.id %}">{{ item.title }}</a></h3>
      {% if user.is_superuser %}
        <form class="inlineBlock" method="post" action="{% url 'article:articleDelete' item.id %}">
          {% csrf_token %}
          <input class="btn" type="submit" value="刪除">
        </form>
      {% endif %}
    <p>發表時間:{{ item.pubDateTime|date:'Y-m-d H:i' }}</p>
    <div class=articleContent>{{ item.content|linebreaks|truncatechars_html:30 }}</div>
    <p>瀏覽次數:{{ item.views }},按讚:{{ item.likes }}</p>
  {% else %}
  <p>
    <span class=comment>{{ item.content }}</span><br>
    <span class=commentTime>{{ item.pubDateTime|date:'m 月 d 日 H:i'}}</span>
  </p>
    {% endif %}
  {% endfor %}
  <hr>
{% endfor %}
{% endblock %}

blog/article/templates/article/articleCreate.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>部落格</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'main/css/main.css' %}">
</head>
<body>
{% include 'main/menu.html' %}
<h2>新增文章</h2>
<form method="post" action="{% url 'article:articleCreate' %}">
 {% csrf_token %}
 {{ articleForm.as_p }}
 <input type="submit" value="送出">
</form>
</body>
</html>

blog/article/templates/article/articleCreateUpdate.html
{% extends 'main/base.html' %}
{% block heading %}
  {% if article %}
    修改文章
  {% else %}
    新增文章
  {% endif %}
{% endblock %}
{% block content %}
{% if article %}
  <form method="post" action="{% url 'article:articleUpdate' article.id %}">
{% else %}
  <form method="post" action="{% url 'article:articleCreate' %}">
{% endif %}
 {% csrf_token %}
 {{ articleForm.as_p }}
 <input type="submit" value="送出">
 <a class="btn" href="{% url 'article:article' %}">放棄</a>
</form>
{% endblock %}

blog/article/templates/article/articleRead.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% block css %}
<link rel="stylesheet" href="{% static 'article/css/article.css' %}">
{% endblock %}
{% block heading %}閱讀文章{% endblock %}
{% block content %}
<h3class="inlineBlock">{{ article.title }}</h3>
{% if user.is_superuser %}
  <a class="btn inlineBlock" href="{% url 'article:articleUpdate' article.id %}">修改</a>
{% endif %}
<p>發表時間:{{ article.pubDateTime|date:'Y-m-d H:i' }}</p>

<div class=articleContent>{{ article.content|linebreaks }}</div>
<p>讚:{{ article.likes }}</p>
{% for comment in comments %}
<p>
<span class=comment>{{ comment.content }}</span><br>
<span class=commentTime>{{ comment.pubDateTime|date:'m 月 d 日 H:i'}}</span>
</p>
{% endfor %}
{% endblock %}

blog/article/templates/article/articleSearch.html
{% extends 'main/base.html' %}
{% block heading %}查詢{% endblock %}
{% block content %}
{% include 'article/searchForm.html' %}
<br><br><hr>
{% if not articles %}
  <p>查無資料</p>
{% else %}
  <table class="table table-striped table-hover">
    <tr><th>標題</th><th>發表時間</th></tr>
    {% for article in articles %}
    <tr>
      <td><a href="{% url 'article:articleRead' article.id %}">{{ article.title }}</a></td>
      <td>{{ article.pubDateTime|date:'Y-m-d H:i' }}</td>
    </tr>
    {% endfor %}
  </table>
{% endif %}
{% endblock %}

blog/article/templates/article/searchForm.html
<form class="inlineBlock" action="{% url 'article:articleSearch' %}">
  <input type="text" name="searchTerm" {% if searchTerm %}value="{{ searchTerm }}"{% endif %}>
  <input class="btn" type="submit" value="查詢">
</form>