blog/account/urls.py
from django.conf.urls import url
from account import views


urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    ]

blog/article/urls.py
from django.conf.urls import url
from article import views


urlpatterns = [
    url(r'^$', views.article, name='article'),
    url(r'^articleCreate/$', views.articleCreate, name='articleCreate'),
    url(r'^articleRead/(?P<articleId>[0-9]+)/$', views.articleRead, name='articleRead'),
    url(r'^articleUpdate/(?P<articleId>[0-9]+)/$', views.articleUpdate, name='articleUpdate'),
    url(r'^articleDelete/(?P<articleId>[0-9]+)/$', views.articleDelete, name='articleDelete'),
    url(r'^articleSearch/$', views.articleSearch, name='articleSearch'),
]

blog/blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^main/', include('main.urls', namespace='main')),
    url(r'^article/', include('article.urls', namespace='article')),
    url(r'^book/', include('book.urls', namespace='book')),
    url(r'^.*', include('main.urls')),
    
]

blog/book/urls.py
from django.conf.urls import url
from book import views


urlpatterns = [
    url(r'^$', views.book, name='book'),
]

blog/main/urls.py
from django.conf.urls import url

from main import views


urlpatterns = [
    url(r'^$', views.main, name='main'),
    url(r'^about/$', views.about, name='about'),
    url(r'^contact/$', views.contact, name='contact'),
]

blog/main/views.py
from django.shortcuts import render, redirect
import datetime
from django.contrib import messages

from blog.settings import LOGIN_URL

def main(request):
    '''
    Render the main page
    '''
    now = datetime.datetime.now()
    context = {'like':'Django', 'now':now}
    return render(request, 'main/main.html', context)


def about(request):
    '''
    Render the "about" page
    '''
    return render(request, 'main/about.html')

def admin_required(func):
    def auth(request, *args, **kwargs):
        if not request.user.is_superuser:
            messages.error(request, '請以管理者身份登入')
            return redirect('account:login')
        return func(request, *args, **kwargs)
    return auth

def contact(request):
    '''
    Render the "contact" page
    '''
    return render(request, 'main/contact.html')

blog/main/templates/main/about.html
{% extends 'main/base.html' %}
{% block heading %}關於{% endblock %}
{% block content %}
<p>歡迎來到我的部落格,您可盡情瀏覽並留言。</p><br>
{% endblock %}

blog/main/templates/main/base.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>部落格</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'main/css/main.css' %}">
{% block css %}{% endblock %}
</head>
<body>
{% include 'main/menu.html' %}
<h2>部落格 -- {% block heading %}{% endblock %}</h2>
{% include 'main/messages.html' %}
{% block content %}{% endblock %}
</body>
</html>

blog/main/templates/main/contact.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>部落格</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'main/css/main.css' %}">
<link rel="icon" href="{% static 'main/img//favicon.ico'%}" type="image/x-icon">
</head>
<body>
{% include 'main/menu.html' %}
<h1>關於我們</h1>
<p>名字：薛孟睿</p>
<p>Emal:jerry1431dd@yahoo.com.tw</p>
<p>地址：</p>
<p><a href="{% url 'main:main' %}">回首頁</a></p>
</body>
</html>

blog/main/templates/main/main.html
{% extends 'main/base.html' %}
{% block heading %}首頁{% endblock %}
{% block content %}
<p>{{ like }}</p>
<p>現在時間:{{ now }}</p>
{% endblock %}

blog/main/templates/main/menu.html
<ul id="menu">
  <li><a href="{% url 'main:main' %}">首頁</a></li>
  <li><a href="{% url 'main:about' %}">關於</a></li>
  <li><a href="{% url 'article:article' %}">部落格</a></li>
  {% if user.is_authenticated %}
  <li><a href="{% url 'account:logout' %}">登出({{ user.username }})</a></li>
  {% else %}
  <li><a href="{% url 'account:register' %}">註冊</a></li>
  <li><a href="{% url 'account:login' %}">登入</a></li>
  {% endif %}
  <li><a href="{% url 'book:book' %}">書籍</a></li>
</ul>

blog/main/templates/main/messages.html
{% for message in messages %}
  <p {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</p>
{% endfor %}